# Generated by Django 5.1.1 on 2025-01-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_event_location_event_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
